
// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: ``
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Server=(local);Database=Cards;Trusted_Connection=True;MultipleActiveResultSets=true`
//     Schema:                 `dbo`
//     Include Views:          `True`

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using PetaPoco;

namespace Cards.Data.Models.Dbo
{
	

    
	[TableName("[dbo].[UserProfile]")]
	[PrimaryKey("UserProfileId")]
	[ExplicitColumns]
    public partial class UserProfile  
    {
		[Key]
		[Column] public Guid UserProfileId { get; set; }
		[Column] public string Username { get; set; }
		[Column] public string PasswordHash { get; set; }
		[Column] public string EmailAddress { get; set; }
		[Column] public string DisplayName { get; set; }
		[Column] public bool IsActive { get; set; }
		[Column] public DateTimeOffset CreatedOn { get; set; }
		[Column] public DateTimeOffset? UpdatedOn { get; set; }
	}
}
