
// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: ``
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Server=(local);Database=Cards;Trusted_Connection=True;MultipleActiveResultSets=true`
//     Schema:                 `dbo`
//     Include Views:          `True`

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using PetaPoco;

namespace Cards.Data.Models.Dbo
{
	

    
	[TableName("dbo.SchemaVersions")]
	[PrimaryKey("Id")]
	[ExplicitColumns]
    public partial class SchemaVersion  
    {
		[Key]
		[Column] public int Id { get; set; }
		[Column] public string ScriptName { get; set; }
		[Column] public DateTime Applied { get; set; }
	}
}
